/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PeerReviewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "checkReviewStatus"
      | "confidentialProtocolId"
      | "createRound"
      | "finalizeRound"
      | "getEncryptedAverageScore"
      | "getEncryptedCount"
      | "getEncryptedTotalScore"
      | "getParticipants"
      | "hasReviewed"
      | "nextRoundId"
      | "rounds"
      | "submitScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RoundCreated" | "RoundFinalized" | "ScoreSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkReviewStatus",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createRound",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedAverageScore",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedCount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalScore",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkReviewStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedAverageScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
}

export namespace RoundCreatedEvent {
  export type InputTuple = [roundId: BigNumberish, participants: AddressLike[]];
  export type OutputTuple = [roundId: bigint, participants: string[]];
  export interface OutputObject {
    roundId: bigint;
    participants: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundFinalizedEvent {
  export type InputTuple = [roundId: BigNumberish];
  export type OutputTuple = [roundId: bigint];
  export interface OutputObject {
    roundId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    reviewer: AddressLike,
    reviewee: AddressLike
  ];
  export type OutputTuple = [
    roundId: bigint,
    reviewer: string,
    reviewee: string
  ];
  export interface OutputObject {
    roundId: bigint;
    reviewer: string;
    reviewee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PeerReview extends BaseContract {
  connect(runner?: ContractRunner | null): PeerReview;
  waitForDeployment(): Promise<this>;

  interface: PeerReviewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  checkReviewStatus: TypedContractMethod<
    [_roundId: BigNumberish, _reviewee: AddressLike, _reviewer: AddressLike],
    [boolean],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createRound: TypedContractMethod<
    [_participants: AddressLike[]],
    [bigint],
    "nonpayable"
  >;

  finalizeRound: TypedContractMethod<
    [_roundId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedAverageScore: TypedContractMethod<
    [_roundId: BigNumberish, _participant: AddressLike],
    [string],
    "view"
  >;

  getEncryptedCount: TypedContractMethod<
    [_roundId: BigNumberish, _participant: AddressLike],
    [string],
    "view"
  >;

  getEncryptedTotalScore: TypedContractMethod<
    [_roundId: BigNumberish, _participant: AddressLike],
    [string],
    "view"
  >;

  getParticipants: TypedContractMethod<
    [_roundId: BigNumberish],
    [string[]],
    "view"
  >;

  hasReviewed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike],
    [boolean],
    "view"
  >;

  nextRoundId: TypedContractMethod<[], [bigint], "view">;

  rounds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, boolean] & {
        roundId: bigint;
        isActive: boolean;
        isFinalized: boolean;
      }
    ],
    "view"
  >;

  submitScore: TypedContractMethod<
    [
      _roundId: BigNumberish,
      _reviewee: AddressLike,
      _encryptedScore: BytesLike,
      _inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkReviewStatus"
  ): TypedContractMethod<
    [_roundId: BigNumberish, _reviewee: AddressLike, _reviewer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createRound"
  ): TypedContractMethod<
    [_participants: AddressLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeRound"
  ): TypedContractMethod<[_roundId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedAverageScore"
  ): TypedContractMethod<
    [_roundId: BigNumberish, _participant: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedCount"
  ): TypedContractMethod<
    [_roundId: BigNumberish, _participant: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedTotalScore"
  ): TypedContractMethod<
    [_roundId: BigNumberish, _participant: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[_roundId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, boolean] & {
        roundId: bigint;
        isActive: boolean;
        isFinalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [
      _roundId: BigNumberish,
      _reviewee: AddressLike,
      _encryptedScore: BytesLike,
      _inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RoundCreated"
  ): TypedContractEvent<
    RoundCreatedEvent.InputTuple,
    RoundCreatedEvent.OutputTuple,
    RoundCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoundFinalized"
  ): TypedContractEvent<
    RoundFinalizedEvent.InputTuple,
    RoundFinalizedEvent.OutputTuple,
    RoundFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;

  filters: {
    "RoundCreated(uint256,address[])": TypedContractEvent<
      RoundCreatedEvent.InputTuple,
      RoundCreatedEvent.OutputTuple,
      RoundCreatedEvent.OutputObject
    >;
    RoundCreated: TypedContractEvent<
      RoundCreatedEvent.InputTuple,
      RoundCreatedEvent.OutputTuple,
      RoundCreatedEvent.OutputObject
    >;

    "RoundFinalized(uint256)": TypedContractEvent<
      RoundFinalizedEvent.InputTuple,
      RoundFinalizedEvent.OutputTuple,
      RoundFinalizedEvent.OutputObject
    >;
    RoundFinalized: TypedContractEvent<
      RoundFinalizedEvent.InputTuple,
      RoundFinalizedEvent.OutputTuple,
      RoundFinalizedEvent.OutputObject
    >;

    "ScoreSubmitted(uint256,address,address)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
  };
}
